name = "serverless-api"
type = "javascript"
account_id = "32c893914da09e7cb225d5e9c6114f45"
workers_dev = true
compatibility_date = "2021-11-04"
route = "*myblog.com/api*"
zone_id = "$zoneId"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
